import Link from "next/link";
import logo from "./logo.svg";
import Image from "next/image";
import "./globals.css";
import { FaGithub, FaLinkedin, FaGlobe } from "react-icons/fa";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <nav className="bg-gray-800 py-4">
        <div className="container mx-auto px-4 flex items-center justify-around">
              <Link href="/" className="text-white text-lg font-semibold">
                <Image src={logo} width={50} height={50} />
              </Link>
              <Link href="/tasks" className="text-white text-lg font-semibold">
                Tasks
              </Link>
              <div className="flex">
              <Link target="_blank" rel="noopener noreferrer" href="https://github.com/speedbuild98">
                <FaGithub className="text-white text-lg font-semibold mr-4 cursor-pointer hover:text-[#f9cc0b]" />
              </Link>
              <Link target="_blank" rel="noopener noreferrer" href="https://www.linkedin.com/in/lautagallardogg/">
                <FaLinkedin className="text-white text-lg font-semibold mr-4 cursor-pointer hover:text-[#f9cc0b]" />
              </Link>
              <Link target="_blank" rel="noopener noreferrer" href="https://gallardolautaro.tech/">
                <FaGlobe className="text-white text-lg font-semibold cursor-pointer hover:text-[#f9cc0b]" />
              </Link>
            </div>
            </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
